name       : pam-wrapper
version    : 1.1.3
release    : 5
source     :
    - https://gitlab.com/cwrap/pam_wrapper/-/archive/pam_wrapper-1.1.3/pam_wrapper-pam_wrapper-1.1.3.tar.bz2 : 1000798737ee61c76644025dc5706a759b64cfa7fe112e0cc80ed3f5e4e8514f
license    : GPL-3.0-or-later
component  : security
summary    : A tool to test PAM applications and PAM modules
description: |
    A tool to test PAM applications and PAM modules
builddeps  :
    - pkgconfig(cmocka)
    - pkgconfig(python3)
setup      : |
    %cmake_ninja -DUNIT_TESTING=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
