name       : pam-wrapper
version    : 1.1.4
release    : 6
source     :
    - https://gitlab.com/cwrap/pam_wrapper/-/archive/pam_wrapper-1.1.4/pam_wrapper-pam_wrapper-1.1.4.tar.gz : 40c4e0697a020584314a4393bdc66d98af97ec239f72d1ba6e9e4a49c7cad9f7
license    : GPL-3.0-or-later
component  : security
summary    : A tool to test PAM applications and PAM modules
description: |
    A tool to test PAM applications and PAM modules
builddeps  :
    - pkgconfig(cmocka)
    - pkgconfig(python3)
setup      : |
    %patch -p1 -i $pkgfiles/drop-python2.diff
    %cmake_ninja -DUNIT_TESTING=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
